apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo_pod
  template:
    metadata:
      name: demo
      labels:
       app: demo_pod
    spec:
      containers:
        - name: demo-pod
          image: aditya9827/demo:1.0.0
          envFrom:
            - configMapRef:
                name: demo-config
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      restartPolicy: Always
