apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo_pod
    type: backend
spec:
  containers:
    - name: demo-pod
      image: aditya9827/demo-k8s
      envFrom:
        - configMapRef:
            name: demo-config
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  