apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo_pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30006
  type: NodePort
  